data "aws_region" "current" {}

locals {
  # Team naming convention: <acronym>-<region>-<context>[-<descriptor>]-<env-type>
  name_mid = "${replace(data.aws_region.current.region, "-", "")}-${var.context}"

  # Standard CloudWatch metrics only (no Container Insights: it is prod only).
  # CloudWatch dimension values derived from ARNs.
  alb_dimension = regex("loadbalancer/(.*)$", var.alb_arn)[0]
  tg_dimensions = { for s, arn in var.target_group_arns : s => regex("(targetgroup/.*)$", arn)[0] }
  # Rule on the default event bus: arn:aws:events:<region>:<account>:rule/<name>
  ingest_rule_name = element(split("/", var.ingest_rule_arn), length(split("/", var.ingest_rule_arn)) - 1)
}

# ---------------------------------------------------------
# ECS: CPU per service. Missing data is notBreaching: a service that restarts publishes
# no datapoints and the healthy hosts alarm covers that case.
# ---------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "service_cpu" {
  for_each = var.service_names

  alarm_name          = "alrm-${local.name_mid}-${each.key}-cpu-${var.env_type}"
  alarm_description   = "CPU utilization of the ${each.key} service is above ${var.service_cpu_threshold_percent} percent"
  namespace           = "AWS/ECS"
  metric_name         = "CPUUtilization"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  datapoints_to_alarm = 3
  threshold           = var.service_cpu_threshold_percent
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    ClusterName = var.cluster_name
    ServiceName = each.value
  }

  alarm_actions = [var.alert_topic_arn]
}

# ---------------------------------------------------------
# ALB: healthy hosts per target group. Missing data is breaching: no datapoint means
# the target group or the load balancer is not reporting, which is itself an outage.
# ---------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "healthy_hosts" {
  for_each = var.target_group_arns

  alarm_name          = "alrm-${local.name_mid}-${each.key}-healthy-hosts-${var.env_type}"
  alarm_description   = "The ${each.key} target group has no healthy target"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HealthyHostCount"
  statistic           = "Minimum"
  period              = 60
  evaluation_periods  = 3
  datapoints_to_alarm = 3
  threshold           = 1
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = "breaching"

  dimensions = {
    TargetGroup  = local.tg_dimensions[each.key]
    LoadBalancer = local.alb_dimension
  }

  alarm_actions = [var.alert_topic_arn]
}

# ---------------------------------------------------------
# ALB: 5XX generated by the load balancer and by the targets. Missing data is
# notBreaching: no traffic means no errors.
# ---------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "alb_5xx" {
  alarm_name          = "alrm-${local.name_mid}-alb-5xx-${var.env_type}"
  alarm_description   = "The load balancer itself returned at least ${var.alb_5xx_threshold} 5XX responses in 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.alb_5xx_threshold
  comparison_operator = "GreaterThanOrEqualToThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = local.alb_dimension
  }

  alarm_actions = [var.alert_topic_arn]
}

resource "aws_cloudwatch_metric_alarm" "target_5xx" {
  alarm_name          = "alrm-${local.name_mid}-target-5xx-${var.env_type}"
  alarm_description   = "The services returned more than ${var.target_5xx_threshold} 5XX responses in 5 minutes"
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.target_5xx_threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = local.alb_dimension
  }

  alarm_actions = [var.alert_topic_arn]
}

# ---------------------------------------------------------
# RDS. Missing data is breaching on the three alarms: an instance that stops reporting
# is a problem, and notBreaching would hide it.
# ---------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "db_free_storage" {
  alarm_name          = "alrm-${local.name_mid}-db-free-storage-${var.env_type}"
  alarm_description   = "The database has less than ${var.db_free_storage_threshold_bytes} bytes of free storage"
  namespace           = "AWS/RDS"
  metric_name         = "FreeStorageSpace"
  statistic           = "Minimum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.db_free_storage_threshold_bytes
  comparison_operator = "LessThanThreshold"
  treat_missing_data  = "breaching"

  dimensions = {
    DBInstanceIdentifier = var.db_instance_identifier
  }

  alarm_actions = [var.alert_topic_arn]
}

resource "aws_cloudwatch_metric_alarm" "db_connections" {
  alarm_name          = "alrm-${local.name_mid}-db-connections-${var.env_type}"
  alarm_description   = "The database has more than ${var.db_connections_threshold} connections"
  namespace           = "AWS/RDS"
  metric_name         = "DatabaseConnections"
  statistic           = "Maximum"
  period              = 300
  evaluation_periods  = 2
  threshold           = var.db_connections_threshold
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "breaching"

  dimensions = {
    DBInstanceIdentifier = var.db_instance_identifier
  }

  alarm_actions = [var.alert_topic_arn]
}

resource "aws_cloudwatch_metric_alarm" "db_cpu" {
  alarm_name          = "alrm-${local.name_mid}-db-cpu-${var.env_type}"
  alarm_description   = "Database CPU utilization is above ${var.db_cpu_threshold_percent} percent"
  namespace           = "AWS/RDS"
  metric_name         = "CPUUtilization"
  statistic           = "Average"
  period              = 300
  evaluation_periods  = 3
  datapoints_to_alarm = 3
  threshold           = var.db_cpu_threshold_percent
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "breaching"

  dimensions = {
    DBInstanceIdentifier = var.db_instance_identifier
  }

  alarm_actions = [var.alert_topic_arn]
}

# ---------------------------------------------------------
# EventBridge: failed target invocations of the ingest rule. Missing data is
# notBreaching: the metric exists only when the rule fires.
# ---------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "ingest_failed_invocations" {
  alarm_name          = "alrm-${local.name_mid}-ingest-failed-invocations-${var.env_type}"
  alarm_description   = "EventBridge could not start the ingestion job for an uploaded file"
  namespace           = "AWS/Events"
  metric_name         = "FailedInvocations"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    RuleName = local.ingest_rule_name
  }

  alarm_actions = [var.alert_topic_arn]
}
